// flow-typed signature: edff7ba52cfdb95d45c858e99e8e69d8
// flow-typed version: <<STUB>>/browserify-middleware_v^7.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserify-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserify-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserify-middleware/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'browserify-middleware/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'browserify-middleware/lib/build-bundle' {
  declare module.exports: any;
}

declare module 'browserify-middleware/lib/build-response' {
  declare module.exports: any;
}

declare module 'browserify-middleware/lib/directory' {
  declare module.exports: any;
}

declare module 'browserify-middleware/lib/file' {
  declare module.exports: any;
}

declare module 'browserify-middleware/lib/modules' {
  declare module.exports: any;
}

declare module 'browserify-middleware/lib/settings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserify-middleware/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'browserify-middleware/coverage/lcov-report/prettify'>;
}
declare module 'browserify-middleware/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'browserify-middleware/coverage/lcov-report/sorter'>;
}
declare module 'browserify-middleware/index' {
  declare module.exports: $Exports<'browserify-middleware'>;
}
declare module 'browserify-middleware/index.js' {
  declare module.exports: $Exports<'browserify-middleware'>;
}
declare module 'browserify-middleware/lib/build-bundle.js' {
  declare module.exports: $Exports<'browserify-middleware/lib/build-bundle'>;
}
declare module 'browserify-middleware/lib/build-response.js' {
  declare module.exports: $Exports<'browserify-middleware/lib/build-response'>;
}
declare module 'browserify-middleware/lib/directory.js' {
  declare module.exports: $Exports<'browserify-middleware/lib/directory'>;
}
declare module 'browserify-middleware/lib/file.js' {
  declare module.exports: $Exports<'browserify-middleware/lib/file'>;
}
declare module 'browserify-middleware/lib/modules.js' {
  declare module.exports: $Exports<'browserify-middleware/lib/modules'>;
}
declare module 'browserify-middleware/lib/settings.js' {
  declare module.exports: $Exports<'browserify-middleware/lib/settings'>;
}
