// flow-typed signature: a0dfbc51f603a7278a1996284616df28
// flow-typed version: <<STUB>>/character-parser_v^2.1.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'character-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'character-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'character-parser/index' {
  declare module.exports: $Exports<'character-parser'>;
}
declare module 'character-parser/index.js' {
  declare module.exports: $Exports<'character-parser'>;
}
