// flow-typed signature: 3f935aa285cf97a40bce250601fa10fe
// flow-typed version: <<STUB>>/leven_v^2.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leven'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'leven' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'leven/index' {
  declare module.exports: $Exports<'leven'>;
}
declare module 'leven/index.js' {
  declare module.exports: $Exports<'leven'>;
}
