// flow-typed signature: 272f07baefd54c1fd38b13a770bc69b0
// flow-typed version: <<STUB>>/lsr_v^1.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lsr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lsr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lsr/index' {
  declare module.exports: $Exports<'lsr'>;
}
declare module 'lsr/index.js' {
  declare module.exports: $Exports<'lsr'>;
}
