// flow-typed signature: ec438ef078eead210b530084ddf927ce
// flow-typed version: <<STUB>>/then-request_v^2.1.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'then-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'then-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'then-request/browser' {
  declare module.exports: any;
}

declare module 'then-request/dist/request' {
  declare module.exports: any;
}

declare module 'then-request/dist/request.min' {
  declare module.exports: any;
}

declare module 'then-request/lib/handle-qs' {
  declare module.exports: any;
}

declare module 'then-request/test/browser' {
  declare module.exports: any;
}

declare module 'then-request/test/get-mock-response' {
  declare module.exports: any;
}

declare module 'then-request/test/index' {
  declare module.exports: any;
}

declare module 'then-request/test/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'then-request/browser.js' {
  declare module.exports: $Exports<'then-request/browser'>;
}
declare module 'then-request/dist/request.js' {
  declare module.exports: $Exports<'then-request/dist/request'>;
}
declare module 'then-request/dist/request.min.js' {
  declare module.exports: $Exports<'then-request/dist/request.min'>;
}
declare module 'then-request/index' {
  declare module.exports: $Exports<'then-request'>;
}
declare module 'then-request/index.js' {
  declare module.exports: $Exports<'then-request'>;
}
declare module 'then-request/lib/handle-qs.js' {
  declare module.exports: $Exports<'then-request/lib/handle-qs'>;
}
declare module 'then-request/test/browser.js' {
  declare module.exports: $Exports<'then-request/test/browser'>;
}
declare module 'then-request/test/get-mock-response.js' {
  declare module.exports: $Exports<'then-request/test/get-mock-response'>;
}
declare module 'then-request/test/index.js' {
  declare module.exports: $Exports<'then-request/test/index'>;
}
declare module 'then-request/test/server.js' {
  declare module.exports: $Exports<'then-request/test/server'>;
}
