// generated by ts-bicycle
// do not edit by hand

import BicycleClient from '../client';

export default class Client<T> extends BicycleClient<T> {
  defineOptimisticUpdaters(updates: T) {
    super.defineOptimisticUpdaters(updates);
  }
}
